application = webapp.WSGIApplication([('/', MainPage),
                                      #('/tuss', test),                                                                                                                                                                                       
                                      ('/deduper', deduper),
                                      ('/deduper_task', deduper_task),
                                      ('/rename', rename),
                                      ('/rename_task', rename_task),
                                      ('/hasher', hasher),
                                      ('/search', SearchPage),
                                      ('/scrape', scrape),
                                      ('/store', Store),
                                      ('/save', Save),
                                      ('/user', UserPage),
                                      ('/removeEntry', RemoveEntry),
                                      ('/removeFresh', RemoveFresh),
                                      ('/removeQuery', DeleteQuery),
                                      ('/remove_task', Remove_Task),
                                      ('/removefreshemail', RemoveFreshEmail),
                                      ('/email_task', Email_Task),
                                      ('/cron_fetch_handler', CronFetchHandler),
                                      ('/email_handler', EmailHandler),
                                      ('/query_handler', QueryHandler),
                                      ('/scrape_handler', scrape_handler),
                                      ('/scrape_page', scrape_page),
                                      ('/scrape_page_handler', scrape_page_handler),
                                      ('/fetch_query', Fetch_Query)],
                                     debug=True)
